### ISSUE TITLE
Error Input Axis  is not setup.

### ISSUE THREAD

**Issue by milos12345** [XRTK/XRTK-Core#336]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

On Play, this error is logged every frame

```
Input Axis  is not setup.
 To change the input settings use: Edit -> Settings -> Input
  at (wrapper managed-to-native) UnityEngine.Input.GetAxisRaw(string)
  at XRTK.Providers.Controllers.UnityInput.GenericJoystickController.UpdateButtonData (XRTK.Definitions.Devices.MixedRealityInteractionMapping interactionMapping) [0x00052] in D:\M\Template\XRTKTemplate9\Library\PackageCache\com.xrtk.core@0.1.19\Providers\Controllers\UnityInput\GenericJoystickController.cs:92 
  at XRTK.Providers.Controllers.UnityInput.GenericJoystickController.UpdateController () [0x00086] in D:\M\Template\XRTKTemplate9\Library\PackageCache\com.xrtk.core@0.1.19\Providers\Controllers\UnityInput\GenericJoystickController.cs:57 
  at XRTK.Providers.Controllers.OpenVR.GenericOpenVRController.UpdateController () [0x0007e] in D:\M\Template\XRTKTemplate9\Library\PackageCache\com.xrtk.core@0.1.19\Providers\Controllers\OpenVR\GenericOpenVRController.cs:164 
  at XRTK.Providers.Controllers.UnityInput.UnityJoystickDataProvider.Update () [0x00059] in D:\M\Template\XRTKTemplate9\Library\PackageCache\com.xrtk.core@0.1.19\Providers\Controllers\UnityInput\UnityJoystickDataProvider.cs:54 
  at XRTK.Services.MixedRealityToolkit.UpdateAllServices () [0x00095] in D:\M\Template\XRTKTemplate9\Library\PackageCache\com.xrtk.core@0.1.19\Services\MixedRealityToolkit.cs:1284 
UnityEngine.Debug:LogError(Object)
XRTK.Services.MixedRealityToolkit:UpdateAllServices() (at Library/PackageCache/com.xrtk.core@0.1.19/Services/MixedRealityToolkit.cs:1288)
XRTK.Services.MixedRealityToolkit:Update() (at Library/PackageCache/com.xrtk.core@0.1.19/Services/MixedRealityToolkit.cs:705)
```

## To Reproduce

Open Unity Hub
New Project with 2019.1.14f1
Choose 3D
Modify the manifest per notes https://github.com/XRTK/XRTK-Core/releases/tag/0.1.19
Includes "com.xrtk.core": "0.1.19",    "com.xrtk.sdk": "0.1.13",    "com.xrtk.wmr": "0.1.5",
Add scene to Build
Restart Unity
Click Configure (crash)
Reopen unity and Click Configure
Press Play

## Your Setup (please complete the following information)

- Unity Version [e.g. 2019.1.14f1]
- XRTK Version 
"com.xrtk.core": "0.1.19",    "com.xrtk.sdk": "0.1.13",    "com.xrtk.wmr": "0.1.5",

## Target Platform (please complete the following information)

- OpenVR

## Additional context

HP Windows Mixed Reality Headset

**Comment by SimonDarksideJ** [comment]
Curious @milos12345 as the latest patches were to resolve this issue and should be sorted in 0.1.19.

Will pull the latest releases and re-test.

P.S. if you created any controller profiles in a previous release, you'll need to either re-generate them or create new ones as the mappings changed.  The defaults in the SDK should be up to date.

Can you please confirm if this is an existing project that you are updating or a new project?

(And Sorry about the Crash, we are still fighting with Unity on that as it's in the Unity editor)

**Comment by milos12345** [comment]
I created a new project with 0.1.19 and the issue is still there. Should I wait for 0.1.20?

**Comment by StephenHodgson** [comment]
Yeah 0.1.20 should fix it.

You can the core project now and test if you like.

**Comment by SimonDarksideJ** [comment]
Issue may not been resolved, darn hard to properly test with the current SDK missmatch.   Finally got it running this morning and still getting the error, investigating.
Will be resolved in 1.20 when it's published

**Comment by SimonDarksideJ** [comment]
OK, latest Core and SDK PR's fully resolve this isue.  Many thanks for pointing this one out @milos12345 , as it also identified another issue with the creation of new profiles, sorted now.
